// <auto-generated />
namespace WaterPolo.Simple.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddCaptionInMatch : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddCaptionInMatch));
        
        string IMigrationMetadata.Id
        {
            get { return "201907100704292_AddCaptionInMatch"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
